### ISSUE TITLE
Compilation error in Fortran code using GCC 10.3.0

### ISSUE THREAD

**Issue by LorienLV** [ECP-WarpX/picsar#24]
I am trying to compile picsar with GCC 10.3.0. It produces the following error:

```
     25    
     26      304 |               bztile, .FALSE., l_lower_order_in_v_in, LVEC_fieldgathe,                &
     27          |                      1
     28    ......
     29     1092 |                 bztile , l4symtry_in, l_lower_order_in_v_in, lvect,                   &
     30          |                         2
  >> 31    Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/LOGICAL(8)).
     32    src/particle_pushers/particle_pusher_manager_3d.F90:318:23:
     33    
     34      318 |               bztile , .FALSE., l_lower_order_in_v_in, lvec_fieldgathe,               &
     35          |                       1
     36    ......
     37     1104 |                 bztile , l4symtry_in, l_lower_order_in_v_in, lvect,                   &
     38          |                         2
  >> 39    Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/LOGICAL(8)).
  >> 40    make: *** [src/particle_pushers/particle_pusher_manager_3d.o] Error 1
```

It seems that it is caused due to some changes in GCC v10. It is possible to circumvent the error by adding '-fallow-argument-mismatch' to the Fortran compiler arguments.

**Comment by ax3l** [comment]
Hi @LorienLV,

thank you for the report!
Many of our colleagues are currently on vacation, but I'll ping some of them so they get a notice on this when they return.

If you already know how to fix this, please do not hesitate to also try and submit a pull request to the repo :)
Seeing this compiler diagnostic from other repos, it might be best to fix it instead of adding the flag, if we can.

cc @hvincenti @lucafedeli88

**Comment by dpgrote** [comment]
The fix I see is to wrap the logical values in a call to `logical`, for example `logical(.FALSE., ISZ)` where `ISZ` is the kind of integers and logicals.
